{{ if (and (.nvim) (eq (get .chezmoi.osRelease "idLike") "debian")) -}}
[".local/bin/nvim"]
    type = "file"
    executable = true
    url = "https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.appimage"
    exact = true


{{ $nerdFontRelease := "3.1.1" -}}
[".local/share/fonts/nerdfont/"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontRelease }}/{{ .nerd_font }}.zip"

{{ $pomodoroVersion := "0.3.0" -}}
[".local/bin/pomodoro"]
    type = "file"
    url = "https://github.com/open-pomodoro/openpomodoro-cli/releases/download/v{{ $pomodoroVersion }}/openpomodoro-cli_{{ $pomodoroVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    [".local/bin/pomodoro".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "pomodoro"]
{{- end }}

{{ if (and (.obsidian) (eq (get .chezmoi.osRelease "idLike") "debian")) -}}
{{ $obsidianVersion := "1.5.3" -}}
[".local/bin/obsidian"]
    type = "file"
    executable = true
    url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ $obsidianVersion }}/Obsidian-{{ $obsidianVersion }}.AppImage"
    exact = true
{{- end }}

{{ if .obsidian }}
["vaults/lifeOS"]
    type = "git-repo"
    url = "git@github.com:SjorsLockhorst/lifeOS.git"

{{- end }}

[".tmux/plugins/tpm/"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    stripComponents = 1

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

{{ if (and (.plasma_i3) (eq (get .chezmoi.osRelease "idLike") "debian")) -}}
[".themes/layan"]
    type = "archive"
    url = "https://github.com/vinceliuice/Layan-kde/archive/refs/tags/2022-02-13.tar.gz"
    stripComponents = 1
[".themes/tela"]
    type = "archive"
    url = "https://github.com/vinceliuice/Tela-icon-theme/archive/refs/tags/2023-02-03.tar.gz"
    stripComponents = 1
{{- end }}
