{{ if (and (.nvim) (eq .chezmoi.os "linux")) -}}
["bin/nvim"]
    type = "file"
    executable = true
    url = "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
    exact = true

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    type = "git-repo"
    url = "https://github.com/wbthomason/packer.nvim"
    depth = 1
{{- end }}


{{ if (and (.zsh) (eq .chezmoi.os "linux")) -}}
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{- end }}

[".tmux/plugins/tpm/"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    stripComponents = 1

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

{{ if (and (.plasma_i3) (eq .chezmoi.os "linux")) -}}
[".themes/layan"]
    type = "archive"
    url = "https://github.com/vinceliuice/Layan-kde/archive/refs/tags/2022-02-13.tar.gz"
    stripComponents = 1
{{- end }}
